### Feature Selection using LASSO

In [296]:
from sklearn import datasets
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [297]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2, random_state=1)

In [298]:
X_train.shape

(614, 8)

In [299]:
X_train.head()

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
663            9      145             80  ...  37.9                     0.637   40
712           10      129             62  ...  41.2                     0.441   38
161            7      102             74  ...  37.2                     0.204   45
509            8      120             78  ...  25.0                     0.409   64
305            2      120             76  ...  39.7                     0.215   29

[5 rows x 8 columns]

In [300]:
from sklearn.preprocessing import StandardScaler

cols = X_train.columns

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=cols)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=cols)

In [301]:
X_train_scaled.head()

Pregnancies   Glucose  ...  DiabetesPedigreeFunction       Age
0     1.516591  0.750524  ...                  0.529526  0.567932
1     1.812018  0.244752  ...                 -0.069689  0.398450
2     0.925736 -0.608739  ...                 -0.794249  0.991638
3     1.221164 -0.039745  ...                 -0.167519  2.601722
4    -0.551400 -0.039745  ...                 -0.760619 -0.364222

[5 rows x 8 columns]

In [302]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.01)

lasso.fit(X_train_scaled, y_train)

Lasso(alpha=0.01)

In [303]:
lasso.coef_

array([ 6.26290474e-02,  1.85968700e-01, -3.50258983e-02, -0.00000000e+00,
       -1.62558777e-04,  8.51781764e-02,  2.83810683e-02,  1.84611338e-02])

In [304]:
import matplotlib.pyplot as plt
import numpy as np

x = pd.Series(np.abs(lasso.coef_), index = cols)

x.sort_values(ascending=False).plot(kind='bar')

<Axes: >

### Feature Selection using Decision Tree

In [305]:
from sklearn import datasets
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [306]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2, random_state=1)

In [307]:
X_train.head()

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
663            9      145             80  ...  37.9                     0.637   40
712           10      129             62  ...  41.2                     0.441   38
161            7      102             74  ...  37.2                     0.204   45
509            8      120             78  ...  25.0                     0.409   64
305            2      120             76  ...  39.7                     0.215   29

[5 rows x 8 columns]

In [308]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

# dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

RandomForestClassifier()

In [309]:
# dt.feature_importances_
rf.feature_importances_

array([0.09051113, 0.25044066, 0.08973696, 0.06799997, 0.07519307,
       0.16860597, 0.12969412, 0.12781812])

In [310]:
x = pd.Series(np.abs(rf.feature_importances_), index=cols)

x.sort_values(ascending=False).plot(kind='bar')

<Axes: >

### SelectFromModel

In [311]:
from sklearn import datasets
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

In [312]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2, random_state=1)

In [313]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

In [314]:
from sklearn.feature_selection import SelectFromModel

sfm = SelectFromModel(model, threshold='mean')

In [315]:
sfm.fit(X_train, y_train)

SelectFromModel(estimator=DecisionTreeClassifier(), threshold='mean')

In [316]:
sfm.get_support(indices=True)

array([1, 5, 7], dtype=int64)

In [317]:
sfm.feature_names_in_[sfm.get_support(indices=True)]

array(['Glucose', 'BMI', 'Age'], dtype=object)

In [318]:
X_train_trans = sfm.transform(X_train)

X_train_trans = pd.DataFrame(X_train_trans, columns=sfm.feature_names_in_[sfm.get_support(indices=True)])

X_train_trans

Glucose   BMI   Age
0      145.0  37.9  40.0
1      129.0  41.2  38.0
2      102.0  37.2  45.0
3      120.0  25.0  64.0
4      120.0  39.7  29.0
..       ...   ...   ...
609    157.0  39.4  30.0
610    187.0  33.9  34.0
611    126.0  43.4  42.0
612    171.0  43.6  26.0
613    102.0  32.9  46.0

[614 rows x 3 columns]

### Recursive Feature Selection

In [319]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [320]:
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [321]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [322]:
from sklearn.ensemble import RandomForestClassifier


rf = RandomForestClassifier()

rf.fit(X, y)

rf.feature_importances_

array([0.07641408, 0.02804047, 0.42075247, 0.47479298])

In [323]:
X.drop(columns='sepal_width', inplace=True)
X.head()

sepal_length  petal_length  petal_width
0           5.1           1.4          0.2
1           4.9           1.4          0.2
2           4.7           1.3          0.2
3           4.6           1.5          0.2
4           5.0           1.4          0.2

In [324]:
rf = RandomForestClassifier()

rf.fit(X, y)

rf.feature_importances_

array([0.18436249, 0.42157415, 0.39406336])

In [325]:
X.drop(columns='sepal_length', inplace=True)
X.head()

petal_length  petal_width
0           1.4          0.2
1           1.4          0.2
2           1.3          0.2
3           1.5          0.2
4           1.4          0.2

In [326]:
rf = RandomForestClassifier()

rf.fit(X, y)

rf.feature_importances_

array([0.49498509, 0.50501491])

In [327]:
X.drop(columns='petal_length', inplace=True)
X.head()

petal_width
0          0.2
1          0.2
2          0.2
3          0.2
4          0.2

### SKLearn RFE

In [328]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load IRIS Dataset
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
df = pd.read_csv(url)

# Separate features and target variable
X = df.drop("species", axis=1)
y = df["species"]

# Initialize RandomForestClassifier
model = RandomForestClassifier()

# Initialize RFE
rfe = RFE(estimator = model, n_features_to_select=1)

# Fit RFE
rfe.fit(X, y)

# Print the Ranking
ranking = rfe.ranking_
print("Feature Ranking: ")

for i, feature in enumerate(X.columns):
    print(f"{feature}: {ranking[i]}")

Feature Ranking: 
sepal_length: 3
sepal_width: 4
petal_length: 2
petal_width: 1
